---
datacenter: /LabUL
resourcePool: /LabUL/host/Cluster-V6.7/Resources
vaultSecretPath: vsphere-labul # pragma: allowlist secret

datastores:
  - /LabUL/datastore/ESX01-Local1
  - /LabUL/datastore/ESX01-Local2
  - /LabUL/datastore/ESX02-Local1
  - /LabUL/datastore/ESX02-Local2
  - /LabUL/datastore/UL-ESX-SAS-02
  - /LabUL/datastore/UL-ESX-SATA-10
  - /LabUL/datastore/UL-ESX-SATA-11

networks:
  - name: LAB-102 (Production)
    path: /LabUL/network/LAB-10.31.102
  - name: LAB-103 (Production)
    path: /LabUL/network/LAB-10.31.103
  - name: LAB-104 (Production)
    path: /LabUL/network/LAB-10.31.104
  - name: MGMT-100 (Management)
    path: /LabUL/network/MGMT-10.31.100

templates:
  - sthings-u22
  - sthings-u24
  - sthings-fedora43

vmFolders:
  - stuttgart-things/testing
  - stuttgart-things/infra
